Console.Clear();
Console.WriteLine("Введите номер дня недели:");
string day = Console.ReadLine();
if (day == "1") Console.WriteLine($"День недели под номером {day} - понедельник");
else if (day == "2") Console.WriteLine($"День недели под номером {day} - вторник");
else if (day == "3") Console.WriteLine($"День недели под номером {day} - среда");
else if (day == "4") Console.WriteLine($"День недели под номером {day} - четверг");
else if (day == "5") Console.WriteLine($"День недели под номером {day} - пятница");
else if (day == "6") Console.WriteLine($"День недели под номером {day} - суббота");
else if (day == "7") Console.WriteLine($"День недели под номером {day} - воскресенье");
else Console.WriteLine("Нет дня недели с данным номером");